/************ This file was generated by parlex ************/

#ifndef plange_GRAMMAR_HPPPP
#define plange_GRAMMAR_HPPPP

#include "parlex/grammar.hpp"
#include "parlex/builtins.hpp"

parlex::grammar const& get_plange();

#endif
