language: c++
addons:
  apt:
    sources:
    - python2.7
    - git
    
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    
before_install:
    - wget https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz -O /tmp/cmake-3.10.0.tar.gz
    - tar -xvf /tmp/cmake-3.10.0.tar.gz
    - export PATH=$PWD/cmake-3.10.0-Linux-x86_64/bin:$PATH
    
script:
    - travis_wait 120 mvn script
    - cd /tmp
    - mkdir -p plange.build
    - cd plange.build
    - cmake $TRAVIS_BUILD_DIR
    - cmake --build .
    
