/************ This file was generated by parlex ************/

#ifndef plange_GRAMMAR_HPP
#define plange_GRAMMAR_HPP

#include "parlex/grammar.hpp"
#include "parlex/builtins.hpp"

parlex::grammar const & get_plange();

#endif
