// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_BINARY_COLLECTION_OP_HPP
#define INCLUDED_BINARY_COLLECTION_OP_HPP
typedef std::variant<
	BIJECTION,
	INTERSECTION,
	SYMMETRIC_DIFFERENCE,
	UNION
> BINARY_COLLECTION_OP;#endif //INCLUDED_BINARY_COLLECTION_OP_HPP