// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_BINARY_ARITHMETIC_OP_HPP
#define INCLUDED_BINARY_ARITHMETIC_OP_HPP
typedef std::variant<
	ADD_SUB,
	ADDITION,
	DIVISION,
	EXPONENTIATION,
	INTEGER_DIVISION,
	MODULATION,
	MULTIPLICATIVE_OP,
	SHIFTL,
	SHIFTR,
	SUBTRACTION
> BINARY_ARITHMETIC_OP;#endif //INCLUDED_BINARY_ARITHMETIC_OP_HPP