// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_DIMENSIONAL_ANALYSIS_OP_HPP
#define INCLUDED_DIMENSIONAL_ANALYSIS_OP_HPP
typedef std::variant<
	UNIT_DIVISION,
	UNIT_EXPONENTIATION,
	UNIT_MULTIPLICATION
> DIMENSIONAL_ANALYSIS_OP;#endif //INCLUDED_DIMENSIONAL_ANALYSIS_OP_HPP