// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_EMBEDDED_NEWLINE_STRING_HPP
#define INCLUDED_EMBEDDED_NEWLINE_STRING_HPP

struct EMBEDDED_NEWLINE_STRING_INTERIOR;

struct EMBEDDED_NEWLINE_STRING {
	erased<EMBEDDED_NEWLINE_STRING_INTERIOR> field_1;
};



#endif //INCLUDED_EMBEDDED_NEWLINE_STRING_HPP
