// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_EMBEDDED_STRING_INTERIOR_HPP
#define INCLUDED_EMBEDDED_STRING_INTERIOR_HPP
typedef std::variant<
	PAYLOAD,
	std::tuple<
		EMBEDDED_STRING_INTERIOR
	>
> EMBEDDED_STRING_INTERIOR;#endif //INCLUDED_EMBEDDED_STRING_INTERIOR_HPP