// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_EMBEDDED_COMMENT_HPP
#define INCLUDED_EMBEDDED_COMMENT_HPP
struct EMBEDDED_COMMENT {
	EMBEDDED_COMMENT_INTERIOR field_1;
};

#endif //INCLUDED_EMBEDDED_COMMENT_HPP