// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_EQUALITY_CHAIN_HPP
#define INCLUDED_EQUALITY_CHAIN_HPP
struct EQUALITY_CHAIN {
	EQUALITY_CHAIN_LOOP EQUALITY_CHAIN_LOOP;
	EXPRESSION EXPRESSION;
	std::vector<IC> field_1;
};

#endif //INCLUDED_EQUALITY_CHAIN_HPP