// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_FUNCTION_MODIFIER_0_HPP
#define INCLUDED_FUNCTION_MODIFIER_0_HPP
typedef std::variant<
	FUNCTION_MODIFIER_STABILITY,
	FUNCTION_MODIFIER_1
> FUNCTION_MODIFIER_0;#endif //INCLUDED_FUNCTION_MODIFIER_0_HPP