// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_FUNCTION_MODIFIER_3_HPP
#define INCLUDED_FUNCTION_MODIFIER_3_HPP
typedef std::variant<
	FUNCTION_MODIFIER_PLATFORM,
	FUNCTION_MODIFIER_4
> FUNCTION_MODIFIER_3;#endif //INCLUDED_FUNCTION_MODIFIER_3_HPP