// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_FUNCTION_MODIFIER_3_HPP
#define INCLUDED_FUNCTION_MODIFIER_3_HPP

struct FUNCTION_MODIFIER_4;
struct FUNCTION_MODIFIER_PLATFORM;

typedef std::variant<
	erased<FUNCTION_MODIFIER_PLATFORM>,
	erased<FUNCTION_MODIFIER_4>
> FUNCTION_MODIFIER_3;

#endif //INCLUDED_FUNCTION_MODIFIER_3_HPP
