// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_FUNCTION_MODIFIER_2_HPP
#define INCLUDED_FUNCTION_MODIFIER_2_HPP

struct FUNCTION_MODIFIER_3;
struct FUNCTION_MODIFIER_ATOMIC;

typedef std::variant<
	erased<FUNCTION_MODIFIER_ATOMIC>,
	erased<FUNCTION_MODIFIER_3>
> FUNCTION_MODIFIER_2;

#endif //INCLUDED_FUNCTION_MODIFIER_2_HPP
