// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_FUNCTION_MODIFIER_4_HPP
#define INCLUDED_FUNCTION_MODIFIER_4_HPP
typedef std::variant<
	FUNCTION_MODIFIER_MODEL,
	FUNCTION_MODIFIER_CALLING_CONVENTION
> FUNCTION_MODIFIER_4;#endif //INCLUDED_FUNCTION_MODIFIER_4_HPP