// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_OP_ASSIGNMENT_HPP
#define INCLUDED_OP_ASSIGNMENT_HPP

#include <optional>
#include <variant>
#include <vector>

#include "val.hpp"

#include "parlex/detail/abstract_syntax_tree.hpp"
#include "parlex/detail/builtins.hpp"
#include "parlex/detail/document.hpp"

#include "plange_grammar.hpp"

namespace plc {

struct ADDITION_ASSIGNMENT;
struct ADD_SUB_ASSIGNMENT;
struct AND_ASSIGNMENT;
struct BIT_AND_ASSIGNMENT;
struct BIT_NOT_ASSIGNMENT;
struct BIT_OR_ASSIGNMENT;
struct BIT_XOR_ASSIGNMENT;
struct COMPOSITION_ASSIGNMENT;
struct COMPOUND_ASSIGNMENT;
struct CROSS_PRODUCT_ASSIGNMENT;
struct DIVISION_ASSIGNMENT;
struct EXPONENTIATION_ASSIGNMENT;
struct FACTORIAL_ASSIGNMENT;
struct IMPLICATION_ASSIGNMENT;
struct INTEGER_DIVISION_ASSIGNMENT;
struct INTERSECTION_ASSIGNMENT;
struct MODULATION_ASSIGNMENT;
struct MULTIPLICATION_ASSIGNMENT;
struct NAND_ASSIGNMENT;
struct NEGATION_ASSIGNMENT;
struct NOR_ASSIGNMENT;
struct NOT_ASSIGNMENT;
struct NULL_COALESCE_ASSIGNMENT;
struct OR_ASSIGNMENT;
struct POST_DEC;
struct POST_INC;
struct PREPEND_ASSIGNMENT;
struct PRE_DEC;
struct PRE_INC;
struct RADICAL_ASSIGNMENT;
struct SHIFTL_ASSIGNMENT;
struct SHIFTR_ASSIGNMENT;
struct SUBTRACTION_ASSIGNMENT;
struct SYMMETRIC_DIFFERENCE_ASSIGNMENT;
struct UNION_ASSIGNMENT;
struct XOR_ASSIGNMENT;

typedef std::variant<
	val<ADD_SUB_ASSIGNMENT>,
	val<ADDITION_ASSIGNMENT>,
	val<AND_ASSIGNMENT>,
	val<BIT_AND_ASSIGNMENT>,
	val<BIT_NOT_ASSIGNMENT>,
	val<BIT_OR_ASSIGNMENT>,
	val<BIT_XOR_ASSIGNMENT>,
	val<COMPOUND_ASSIGNMENT>,
	val<COMPOSITION_ASSIGNMENT>,
	val<CROSS_PRODUCT_ASSIGNMENT>,
	val<DIVISION_ASSIGNMENT>,
	val<EXPONENTIATION_ASSIGNMENT>,
	val<FACTORIAL_ASSIGNMENT>,
	val<IMPLICATION_ASSIGNMENT>,
	val<INTEGER_DIVISION_ASSIGNMENT>,
	val<INTERSECTION_ASSIGNMENT>,
	val<MODULATION_ASSIGNMENT>,
	val<MULTIPLICATION_ASSIGNMENT>,
	val<NAND_ASSIGNMENT>,
	val<NEGATION_ASSIGNMENT>,
	val<NOR_ASSIGNMENT>,
	val<NOT_ASSIGNMENT>,
	val<NULL_COALESCE_ASSIGNMENT>,
	val<OR_ASSIGNMENT>,
	val<PRE_DEC>,
	val<PRE_INC>,
	val<PREPEND_ASSIGNMENT>,
	val<POST_DEC>,
	val<POST_INC>,
	val<RADICAL_ASSIGNMENT>,
	val<SHIFTL_ASSIGNMENT>,
	val<SHIFTR_ASSIGNMENT>,
	val<SUBTRACTION_ASSIGNMENT>,
	val<SYMMETRIC_DIFFERENCE_ASSIGNMENT>,
	val<UNION_ASSIGNMENT>,
	val<XOR_ASSIGNMENT>
> OP_ASSIGNMENT_base;

struct OP_ASSIGNMENT: OP_ASSIGNMENT_base {
	static OP_ASSIGNMENT build(parlex::detail::ast_node const & n);
	explicit OP_ASSIGNMENT(OP_ASSIGNMENT_base const & value) : OP_ASSIGNMENT_base(value) {}
	static parlex::detail::acceptor const & acceptor();
};
} // namespace plc



#endif //INCLUDED_OP_ASSIGNMENT_HPP
