// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_TYPE_SCOPE_TYPE_CONSTRAINT_HPP
#define INCLUDED_TYPE_SCOPE_TYPE_CONSTRAINT_HPP
struct TYPE_SCOPE_TYPE_CONSTRAINT {
	TYPE_CONSTRAINT_HEAD field_1;
	std::vector<IC> field_2;
	TYPE_SCOPE_TYPE_CONSTRAINT_CHAIN field_3;
};

#endif //INCLUDED_TYPE_SCOPE_TYPE_CONSTRAINT_HPP