// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_UNIT_MULTIPLICATION_HPP
#define INCLUDED_UNIT_MULTIPLICATION_HPP
struct UNIT_MULTIPLICATION {
	DIMENSION field_1;
	DIMENSION field_2;
};

#endif //INCLUDED_UNIT_MULTIPLICATION_HPP