// This file was generated using Parlex's cpp_generator

#ifndef INCLUDED_UNIT_EXPONENTIATION_HPP
#define INCLUDED_UNIT_EXPONENTIATION_HPP
struct UNIT_EXPONENTIATION {
	DIMENSION field_1;
	NON_FRACTIONAL field_2;
};

#endif //INCLUDED_UNIT_EXPONENTIATION_HPP