/************ This file was generated by parlex ************/

#ifndef precedence_GRAMMAR_HPP
#define precedence_GRAMMAR_HPP

#include "parlex/grammar.hpp"
#include "parlex/builtins.hpp"

parlex::grammar const & get_precedence();

#endif
